### ISSUE TITLE
Document compatibility with other OS than Windows

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-plugin-qgis#73]
- [x] Windows 10
- [x] Windows 8.1
- [x] Windows 7
- [x] Mac OS X
- [ ] Ubuntu 14.04 (Debian)
- [ ] Ubuntu 16.04 (Debian)

**Comment by TheoSinatti** [comment]
**Explanations about the Mac OS compatibility**
Fixed the language problem that existed when used on Mac OS. 
The GUI problem with the keywords combobox can be fixed by changing QGIS style (Settings/Options/General/Style). Default style Macintosh, and Cleanlooks, don't work well with the plugin. Any other one (Plastic, CDE, Windows, and Motif) work. Isogeo staff kindly recommand Plastic, by far the best one.
